### ISSUE TITLE
time variable in get_eurostat_data function

### ISSUE THREAD

**Issue by greg-dubrow** [milos-agathon/how-i-make-eurostat-maps#1]
Love the tutorial, super helpful, just one minor error it's throwing:

In the get_eurostat_data function perhaps the API has changed? What you have here as "time" now needs to be called as "TIME_PERIOD". Found out by calling the table independently of the function and looking at variable names.

get_eurostat_data <- function() {
    eurostat_df <- eurostat::get_eurostat(
        "nama_10r_2gdp",
        time_format = "num"
    ) |>
        dplyr::filter(
            unit == "PPS_EU27_2020_HAB" &
                time >= 2020
        ) |>
        dplyr::select(geo, time, values)
    names(eurostat_df)[1] <- "NUTS_ID"
    return(eurostat_df)
}

**Comment by milos-agathon** [comment]
Hi Greg, indeed, the API has changed and you can find the updated code here:
https://github.com/milos-agathon/eurostat-maps-2024/blob/main/R/main.r

**Comment by greg-dubrow** [comment]
Ah, thanks. Hadn't seen that post. I didn't use the Eurostat part but I did use some code for the map here:

https://www.gregdubrow.io/posts/30-day-chart-challenge-2024/#prompt7

Thanks for these tutorials, they're all so interesting and helpful.
